
## TD forecast on python

Version 0 (Release cuối tháng 12) này gồm 2 subproject:
- TD Forecast bases on as-is model
- TD Market line forecast

Version 1, dự án sẽ được hoàn thiện hơn với 
- Các thuật toán chuyên sâu của machine learning
- Áp dụng kết hợp bộ dữ liệu forecast từ marketline 

Giả định:
- ...


Kỳ vọng V1:
- Biên độ lệch thực tế từng cấu phần cho phép +-70%
-

## AUTO EXECUTION

### 1. DATA COLLECTION

#### 1.1. Data Manual Adjustment

#### 1.2. DataMart Updated

In [6]:
import pyodbc
import pandas as pd
from TD_DeepFunction_hien import *

import pandas as pd
import numpy as np



# server = '10.16.157.42'
# database = 'RB_DATA'

In [27]:
""" 
Giải thích hàm

SQL_DEPS_MOVEMENT_11(Month_start,server,database): 
- Quét dữ liệu theo '1.1 DEPS_MOV.sql', chạy từ Month_start đến ngày query
- INDICATOR: EOP

SQL_DEPS_MOVEMENT_GROUPTERM(dataframe)
- Tạo thêm trường dữ liệu group nhóm term cho bảng dữ liệu SQL_DEPS_MOVEMENT_11 vừa tạo
- 

SQL_SD_OTHER_14(Month_end,server,database)
- 

SQL_SD_OTHER_14_V2(server,database)
- Dự chứa dữ liệu của cả năm 2023 (hiện còn thiếu full tháng 12)
- CODE: CIE, VOF, ADB
"""

" \nGiải thích hàm\n\nSQL_DEPS_MOVEMENT_11(Month_start,server,database): \n- Quét dữ liệu theo '1.1 DEPS_MOV.sql', chạy từ Month_start đến ngày query\n- INDICATOR: EOP\n\nSQL_DEPS_MOVEMENT_GROUPTERM(dataframe)\n- Tạo thêm trường dữ liệu group nhóm term cho bảng dữ liệu SQL_DEPS_MOVEMENT_11 vừa tạo\n- \n\nSQL_SD_OTHER_14(Month_end,server,database)\n- \n\nSQL_SD_OTHER_14_V2(server,database)\n- Dự chứa dữ liệu của cả năm 2023 (hiện còn thiếu full tháng 12)\n- CODE: CIE, VOF, ADB\n"

In [13]:
df_movement = SQL_DEPS_MOVEMENT_11('2023-01','2023-10',server,database)


## FOR UAT: số dòng ở file excel là 5960

NameError: name 'server' is not defined

In [55]:
df_movement_term = SQL_DEPS_MOVEMENT_GROUPTERM(df_movement)
df_movement_term

,PERIOD,PRODUCT_GROUP,TERM,CURRENCY,STATUS_LM,STATUS_CM,MOVEMENT_TYPE,BIG_TD_CM,BIG_TD_LM,EOP_LM,EOP_CM,NET,MAT_INSTRUCTION,Term_CM,Term_LM,Currency_2,TYPE
0,2023-01,TD,None,None,None,None,0UNCHANGED_NOTROLL,None,None,0.000000e+00,0.000000e+00,0.000000e+00,Payment to nominated account,less than 1M,less than 1M,VND,NOT_ROLL
1,2023-01,TD,None,None,None,None,4UNCHANGED_AUTOROLL,None,None,0.000000e+00,0.000000e+00,0.000000e+00,AUTOMATIC ROLLOVER,less than 1M,less than 1M,VND,AUTOROLL
2,2023-01,TD,None,None,None,None,9OTHERS,None,None,0.000000e+00,0.000000e+00,0.000000e+00,None,less than 1M,less than 1M,VND,NOT_ROLL
3,2023-01,TD,None,USD,None,None,9OTHERS,MASS,MASS,2.370000e-07,2.340000e-07,-3.000000e-09,None,less than 1M,less than 1M,Non-VND,NOT_ROLL
4,2023-01,TD,None,VND,None,None,9OTHERS,MASS,MASS,1.434754e-01,1.434754e-01,0.000000e+00,None,less than 1M,less than 1M,VND,NOT_ROLL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5955,2023-10,TD,9M,VND,9M,9M,6ROLL_AUTOROLL,MASS,MASS,1.143989e+01,1.196627e+01,5.263821e-01,AUTOMATIC ROLLOVER,6-9M,6-9M,VND,AUTOROLL
5956,2023-10,TD,9M,VND,9M,9M,7PREMATURE_AUTOROLL,MASS,MASS,1.533056e+01,0.000000e+00,-1.533056e+01,AUTOMATIC ROLLOVER,6-9M,6-9M,VND,AUTOROLL
5957,2023-10,TD,9M,VND,9M,9M,9OTHERS,BIG_TD,BIG_TD,0.000000e+00,2.500000e+01,2.500000e+01,AUTOMATIC ROLLOVER,6-9M,6-9M,VND,AUTOROLL
5958,2023-10,TD,9M,VND,9M,9M,9OTHERS,MASS,MASS,1.055171e+01,1.761721e+01,7.065492e+00,AUTOMATIC ROLLOVER,6-9M,6-9M,VND,AUTOROLL
5959,2023-10,TD,9M,VND,9M,9M,9OTHERS,MASS,MASS,9.847800e+00,2.469256e+01,1.484476e+01,PAYMENT TO NOMINATED ACCOUNT,6-9M,6-9M,VND,NaN

In [7]:
# df_movement_term.to_excel(r'C:\Users\hiennpd3\OneDrive - VPBank\AA Team\2. TD forecast model\df_movement_term.xlsx', index=False)
df_movement_term = pd.read_excel('/Users/nguyenhien/Desktop/Package/df_movement_term.xlsx')

In [8]:
df_movement_term

,PERIOD,PRODUCT_GROUP,TERM,CURRENCY,STATUS_LM,STATUS_CM,MOVEMENT_TYPE,BIG_TD_CM,BIG_TD_LM,EOP_LM,EOP_CM,NET,MAT_INSTRUCTION,Term_CM,Term_LM,Currency_2,TYPE
0,2023-01,TD,NaN,NaN,NaN,NaN,0UNCHANGED_NOTROLL,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,Payment to nominated account,less than 1M,less than 1M,VND,NOT_ROLL
1,2023-01,TD,NaN,NaN,NaN,NaN,4UNCHANGED_AUTOROLL,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,AUTOMATIC ROLLOVER,less than 1M,less than 1M,VND,AUTOROLL
2,2023-01,TD,NaN,NaN,NaN,NaN,9OTHERS,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,NaN,less than 1M,less than 1M,VND,NOT_ROLL
3,2023-01,TD,NaN,USD,NaN,NaN,9OTHERS,MASS,MASS,2.370000e-07,2.340000e-07,-3.000000e-09,NaN,less than 1M,less than 1M,Non-VND,NOT_ROLL
4,2023-01,TD,NaN,VND,NaN,NaN,9OTHERS,MASS,MASS,1.434754e-01,1.434754e-01,0.000000e+00,NaN,less than 1M,less than 1M,VND,NOT_ROLL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5955,2023-10,TD,9M,VND,9M,9M,6ROLL_AUTOROLL,MASS,MASS,1.143989e+01,1.196627e+01,5.263821e-01,AUTOMATIC ROLLOVER,6-9M,6-9M,VND,AUTOROLL
5956,2023-10,TD,9M,VND,9M,9M,7PREMATURE_AUTOROLL,MASS,MASS,1.533056e+01,0.000000e+00,-1.533056e+01,AUTOMATIC ROLLOVER,6-9M,6-9M,VND,AUTOROLL
5957,2023-10,TD,9M,VND,9M,9M,9OTHERS,BIG_TD,BIG_TD,0.000000e+00,2.500000e+01,2.500000e+01,AUTOMATIC ROLLOVER,6-9M,6-9M,VND,AUTOROLL
5958,2023-10,TD,9M,VND,9M,9M,9OTHERS,MASS,MASS,1.055171e+01,1.761721e+01,7.065492e+00,AUTOMATIC ROLLOVER,6-9M,6-9M,VND,AUTOROLL
5959,2023-10,TD,9M,VND,9M,9M,9OTHERS,MASS,MASS,9.847800e+00,2.469256e+01,1.484476e+01,PAYMENT TO NOMINATED ACCOUNT,6-9M,6-9M,VND,NaN

In [4]:
df_sd_other = SQL_SD_OTHER_14(server,database)
df_sd_other

Completed fetch SQL_DEPS_MOVEMENT: 1886 rows

     CODE   PERIOD PRODUCT MIS_TERM CURRENCY_REFINE VINTAGE     AMOUNT
0     VOF  2023-02      TD      57M             VND           0.004329
1     CIE  2023-02      TD     120M             VND          -0.002331
2     VOF  2023-02      TD      96M             VND           0.000019
3     VOF  2023-02      TD       7M             VND           4.004925
4     CIE  2023-02      TD       5M             VND          -0.319279
...   ...      ...     ...      ...             ...     ...        ...
1881  VOF  2023-10      TD      96M             VND           0.000021
1882  VOF  2023-10      TD       7M             VND          71.410229
1883  VOF  2023-10      TD       6M         NON-VND           0.061955
1884  CIE  2023-10      TD       5M             VND          -0.356774
1885  VOF  2023-10      TD       2W         NON-VND           0.009366

[1886 rows x 7 columns]

In [10]:
# df_sd_other.to_excel(r'C:\Users\hiennpd3\OneDrive - VPBank\AA Team\2. TD forecast model\df_sd_other.xlsx', index=False)
df_sd_other = pd.read_excel('/Users/nguyenhien/Desktop/Package/df_sd_other.xlsx')
df_sd_other

     CODE   PERIOD PRODUCT MIS_TERM CURRENCY_REFINE  VINTAGE     AMOUNT
0     VOF  2023-02      TD      57M             VND      NaN   0.004329
1     CIE  2023-02      TD     120M             VND      NaN  -0.002331
2     VOF  2023-02      TD      96M             VND      NaN   0.000019
3     VOF  2023-02      TD       7M             VND      NaN   4.004925
4     CIE  2023-02      TD       5M             VND      NaN  -0.319279
...   ...      ...     ...      ...             ...      ...        ...
1881  VOF  2023-10      TD      96M             VND      NaN   0.000021
1882  VOF  2023-10      TD       7M             VND      NaN  71.410229
1883  VOF  2023-10      TD       6M         NON-VND      NaN   0.061955
1884  CIE  2023-10      TD       5M             VND      NaN  -0.356774
1885  VOF  2023-10      TD       2W         NON-VND      NaN   0.009366

[1886 rows x 7 columns]

In [5]:
## IMPORT MANUALLY DATA - EOP/CLOSSINGBALANCE/CIE/FT
file_path = r"C:\Users\hiennpd3\OneDrive - VPBank\AA Team\2. TD forecast model\Manual_input_data.xlsx"

df_input_deps = pd.read_excel(file_path, header=0, skiprows=0)

In [11]:
df_input_deps = pd.read_excel('/Users/nguyenhien/Desktop/Package/df_input_deps.xlsx')
df_input_deps

,VINTAGE,FINANCIAL_ITEM,Product_Group,Type,Term,Currency,2023-01,2023-02,2023-03,2023-04,...,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
0,ALL,Closing Balance,TD,ALL,less than 1M,VND,164.626443,158.718129,126.394337,283.691146,...,1202.896754,1429.255814,2393.958283,3335.219557,4133.165871,4816.968591,5968.828717,6954.848027,8622.153526,10781.294096
1,ALL,Closing Balance,TD,ALL,1-3M,VND,17708.480850,16161.183745,16001.726861,16171.603175,...,23970.743805,24788.199762,25092.722357,25719.819015,26816.199990,27447.226579,28077.906294,29047.437420,29999.863646,32593.813501
2,ALL,Closing Balance,TD,ALL,4-5M,VND,187.252349,173.695511,196.021930,172.665172,...,239.216204,241.843532,246.809494,252.190523,341.197993,431.465211,440.353650,510.854630,575.353278,699.144511
3,ALL,Closing Balance,TD,ALL,6-9M,VND,84753.339546,91063.521597,97425.049437,101688.784366,...,138821.076694,142406.871849,145362.679714,148617.760293,150741.812855,153716.260000,155851.541070,157216.692074,157878.461085,161560.805367
4,ALL,Closing Balance,TD,ALL,10-11M,VND,179.516758,254.940242,325.797188,369.207312,...,548.363262,554.385972,565.769612,524.760685,438.519347,366.244625,406.502723,364.798599,339.509609,240.050445
5,ALL,Closing Balance,TD,ALL,12-18M,VND,50615.350016,58585.072539,64849.833817,71092.648388,...,80462.092580,80629.637333,81606.592740,82763.462029,84023.421183,84975.620441,85800.348564,87179.677803,88110.121965,85166.971681
6,ALL,Closing Balance,TD,ALL,From 18M,VND,1609.831579,1939.461596,1938.674092,1927.905824,...,1741.216714,1734.762907,1705.126859,1528.926491,1465.297970,1499.485191,1477.084546,1463.754000,1470.017684,946.126722
7,ALL,Closing Balance,TD,ALL,less than 1M,NON-VND,9.441694,10.659119,12.685246,7.934855,...,12.959447,13.101782,13.370811,13.662326,14.032107,14.300084,14.594674,14.991328,15.412461,16.027735
8,ALL,Closing Balance,TD,ALL,1-3M,NON-VND,323.778039,378.797624,306.265102,313.022835,...,333.556991,337.220470,344.144881,351.648052,361.165659,368.062996,375.645311,385.854577,426.782621,422.960109
9,ALL,Closing Balance,TD,ALL,4-5M,NON-VND,1.091611,1.107114,0.935040,0.935693,...,1.235660,1.249231,1.274883,1.302678,1.337936,1.363487,1.391576,1.429396,1.469550,1.528216
10,ALL,Closing Balance,TD,ALL,6-9M,NON-VND,476.192243,393.102186,380.427225,367.890741,...,342.839661,346.605092,353.722205,334.762164,362.085355,365.898358,369.215017,383.223989,392.751229,407.872082
11,ALL,Closing Balance,TD,ALL,10-11M,NON-VND,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,ALL,Closing Balance,TD,ALL,12-18M,NON-VND,341.005129,343.980600,322.619285,313.902832,...,295.418101,273.084990,291.743915,271.432601,265.082161,205.004718,172.821263,195.945268,171.546771,161.269291
13,ALL,Closing Balance,TD,ALL,From 18M,NON-VND,84.587982,85.828257,81.820680,81.788302,...,81.171627,56.485432,70.696749,45.566085,33.102406,24.428886,36.012428,32.655388,32.644074,36.136244
14,Newbooks,CIE Rate,TD,ALL,less than 1M,VND,-0.005000,-0.005000,-0.005000,-0.005000,...,-0.005000,-0.005000,-0.005000,-0.005000,-0.005000,-0.005000,-0.005000,-0.005000,-0.005000,-0.005000
15,Newbooks,CIE Rate,TD,ALL,1-3M,VND,-0.059963,-0.059989,-0.059991,-0.054938,...,-0.038800,-0.038800,-0.038800,-0.038800,-0.038800,-0.037800,-0.036800,-0.035800,-0.035800,-0.035800
16,Newbooks,CIE Rate,TD,ALL,4-5M,VND,-0.059948,-0.059942,-0.059992,-0.054593,...,-0.037800,-0.037800,-0.037800,-0.037800,-0.037800,-0.036800,-0.035800,-0.037500,-0.037500,-0.037500
17,Newbooks,CIE Rate,TD,ALL,6-9M,VND,-0.094140,-0.094872,-0.092083,-0.087620,...,-0.054000,-0.054000,-0.054000,-0.054000,-0.054000,-0.053000,-0.052000,-0.051500,-0.051500,-0.051500
18,Newbooks,CIE Rate,TD,ALL,10-11M,VND,-0.092921,-0.091796,-0.089087,-0.086499,...,-0.053500,-0.053500,-0.053500,-0.053500,-0.053500,-0.052500,-0.051500,-0.050500,-0.050500,-0.050500
19,Newbooks,CIE Rate,TD,ALL,12-18M,VND,-0.096168,-0.097497,-0.093078,-0.089647,...,-0.053500,-0.053500,-0.053500,-0.053500,-0.053500,-0.052500,-0.051500,-0.050500,-0.050500,-0.050500
20,Newbooks,CIE Rate,TD,ALL,From 18M,VND,-0.090636,-0.091409,-0.086171,-0.074882,...,-0.053500,-0.053500,-0.053500,-0.053500,-0.053500,-0.052500,-0.051500,-0.050500,-0.050500,-0.050500
21,Newbooks,CIE Rate,TD,ALL,less than 1M,Non-VND,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,Newbooks,CIE Rate,TD,ALL,1-3M,Non-VND,-0.000249,-0.000263,-0.000312,-0.000750,...,-0.000331,-0.000331,-0.000331,-0.000331,-0.000331,-0.000331,-0.000331,-0.000331,-0.000331,-0.000331
23,Newbooks,CIE Rate,TD,ALL,4-5M,Non-VND,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,Newbooks,CIE Rate,TD,ALL,6-9M,Non-VND,-0.001411,-0.000972,-0.002065,-0.000598,...,-0.000980,-0.000980,-0.000980,-0.000980,-0.000980,-0.000980,-0.000980,-0.000980,-0.000980,-0.000980
25,Newbooks,CIE Rate,TD,ALL,10-11M,Non-VND,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,Newbooks,CIE Rate,TD,ALL,12-18M,Non-VND,-0.000620,-0.000324,-0.001006,-0.000276,...,-0.000799,-0.000799,-0.000799,-0.000799,-0.000799,-0.000799,-0.000799,-0.000799,-0.000799,-0.000799
27,Newbooks,CIE Rate,TD,ALL,From 18M,Non-VND,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,Newbooks,FTP Rate,TD,ALL,less than 1M,VND,0.062963,0.062787,0.062968,0.057719,...,0.016000,0.016000,0.016000,0.016000,0.016000,0.015000,0.014000,0.013000,0.013000,0.013000
29,Newbooks,FTP Rate,TD,ALL,1-3M,VND,0.068119,0.068110,0.068099,0.063345,...,0.050500,0.050500,0.050500,0.050500,0.050500,0.049500,0.048500,0.047500,0.047500,0.047500
30,Newbooks,FTP Rate,TD,ALL,4-5M,VND,0.070243,0.070305,0.070482,0.065365,...,0.050500,0.050500,0.050500,0.050500,0.050500,0.049500,0.048500,0.047500,0.047500,0.047500
31,Newbooks,FTP Rate,TD,ALL,6-9M,VND,0.112546,0.112657,0.106843,0.102341,...,0.063000,0.063000,0.063000,0.063000,0.063000,0.062000,0.061000,0.060000,0.060000,0.060000
32,Newbooks,FTP Rate,TD,ALL,10-11M,VND,0.113500,0.113500,0.107404,0.103395,...,0.063000,0.063000,0.063000,0.063000,0.063000,0.062000,0.061000,0.060000,0.060000,0.060000
33,Newbooks,FTP Rate,TD,ALL,12-18M,VND,0.118927,0.118961,0.110652,0.106695,...,0.063000,0.063000,0.063000,0.063000,0.063000,0.062000,0.061000,0.060000,0.060000,0.060000
34,Newbooks,FTP Rate,TD,ALL,From 18M,VND,0.121334,0.121303,0.114429,0.093198,...,0.063000,0.063000,0.063000,0.063000,0.063000,0.062000,0.061000,0.060000,0.060000,0.060000
35,Newbooks,FTP Rate,TD,ALL,less than 1M,Non-VND,0.037061,0.037290,0.037129,0.037109,...,0.030956,0.030956,0.030956,0.030956,0.030956,0.030956,0.030956,0.030956,0.030956,0.030956
36,Newbooks,FTP Rate,TD,ALL,1-3M,Non-VND,0.033058,0.034150,0.031685,0.064181,...,0.029586,0.029586,0.029586,0.029586,0.029586,0.029586,0.029586,0.029586,0.029586,0.029586
37,Newbooks,FTP Rate,TD,ALL,4-5M,Non-VND,0.036694,0.044500,0.000000,0.000000,...,0.043520,0.043520,0.043520,0.043520,0.043520,0.043520,0.043520,0.043520,0.043520,0.043520
38,Newbooks,FTP Rate,TD,ALL,6-9M,Non-VND,0.032914,0.029312,0.063989,0.035644,...,0.021856,0.021856,0.021856,0.021856,0.021856,0.021856,0.021856,0.021856,0.021856,0.021856
39,Newbooks,FTP Rate,TD,ALL,10-11M,Non-VND,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
40,Newbooks,FTP Rate,TD,ALL,12-18M,Non-VND,0.035654,0.034838,0.022753,0.036074,...,0.018656,0.018656,0.018656,0.018656,0.018656,0.018656,0.018656,0.018656,0.018656,0.018656
41,Newbooks,FTP Rate,TD,ALL,From 18M,Non-VND,0.049000,0.050000,0.049000,0.049000,...,0.018953,0.018953,0.018953,0.018953,0.018953,0.018953,0.018953,0.018953,0.018953,0.018953

In [78]:
# df_input_deps.to_excel(r'C:\Users\hiennpd3\OneDrive - VPBank\AA Team\2. TD forecast model\df_input_deps.xlsx', index=False)

### 2. MODEL

In [ ]:
#Target: tạo ra một bảng kết quả model : USER_DATA.HIENNPD3.FCST_RESULTS_TD_ALL
# BAO GỒM: Vintages,	Financial_Items,	Type,	Term_CM,	Currency_2,	Period,	Indicators, Month_ID, Month_end, Value
# Financial_Items: ADB
# Indicators = ['1. Opening Balance',  '3. Closing Balance' , '2.1 Not-roll: New sales','2.1 Not-roll: Schedule on system','2.1 Not-roll: Premature', '2.2 Autoroll: New sales','2.2 Autoroll: Roll','2.2 Autoroll: Premature', '2.3 Other']
# Supported equation: |1 - 3| = |Sum 2|

In [12]:

# Tạo DataFrame với mapping chuẩn.
months = []
for year in range(2023, 2025):
    for month in range(1, 13):
        month_str = f"{year}-{month:02}"
        months.append(month_str)

Period = np.array(months, dtype='object')

FCST_RESULTS_TD_ALL = pd.DataFrame(columns=['Vintages', 'Financial_Items', 'Type', 'Term_CM', 'Currency_2', 'Period', 'Indicators', 'Month_ID', 'Month_end', 'Value'])

Term_CM = df_movement_term['Term_CM'].unique()
Currency_2 = df_movement_term['Currency_2'].unique()
Indicator = ['1. Opening Balance',  
                          '3. Closing Balance' , 
                          '2.1 Not-roll: New sales',
                          '2.1 Not-roll: Schedule on system',
                          '2.1 Not-roll: Premature', 
                          '2.2 Autoroll: New sales',
                          '2.2 Autoroll: Roll',
                          '2.2 Autoroll: Premature', 
                          '2.3 Other',
                        '%Premature Not-roll/EOP Not-roll',
                        '%Premature Autoroll/EOP Autoroll',
                        '%Roll_Autoroll',
                        '%NewNot-roll',
                        '%New Autoroll',
                        '%Schedule/Not-roll'
                        ]

Term_CM, Currency_2, Period, Indicator = np.meshgrid(Term_CM, Currency_2, Period, Indicator)
Term_CM = Term_CM.flatten()
Currency_2 = Currency_2.flatten()
Period = Period.flatten()
Indicator = Indicator.flatten()


df = pd.DataFrame({'Vintages': 'ALL',
                   'Financial_items' : 'EOP',
                   'Type': 'ALL',
                   'Term_CM': Term_CM, 
                   'Currency_2': Currency_2,
                   'PERIOD': Period,
                   'INDICATORS': Indicator
                   })
df

,Vintages,Financial_items,Type,Term_CM,Currency_2,PERIOD,INDICATORS
0,ALL,EOP,ALL,less than 1M,VND,2023-01,1. Opening Balance
1,ALL,EOP,ALL,less than 1M,VND,2023-01,3. Closing Balance
2,ALL,EOP,ALL,less than 1M,VND,2023-01,2.1 Not-roll: New sales
3,ALL,EOP,ALL,less than 1M,VND,2023-01,2.1 Not-roll: Schedule on system
4,ALL,EOP,ALL,less than 1M,VND,2023-01,2.1 Not-roll: Premature
...,...,...,...,...,...,...,...
5755,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%Premature Autoroll/EOP Autoroll
5756,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%Roll_Autoroll
5757,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%NewNot-roll
5758,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%New Autoroll
5759,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%Schedule/Not-roll

In [23]:
# # Tạo hàm tùy chỉnh để lấy giá trị từ df_movement_term
# def Value_Opening_Balance(row):
#     if row['INDICATORS'] == '1. Opening Balance':
#         term_cm = row['Term_CM']
#         currency_2 = row['Currency_2']
#         period = row['PERIOD']

#         value = df_movement_term.loc[
#             (df_movement_term['Term_CM'] == term_cm) 
#             & (df_movement_term['Currency_2'] == currency_2)
#             & (df_movement_term['PERIOD'] == period)
#             , 'EOP_LM'
#         ].values

#         # Trả về giá trị hoặc 0 nếu không tìm thấy
#         if len(value) > 0:
#             return value.sum()
#         else:
#             return 0
#     else:  # Added 'else' to fix indentation
#         term_cm = row['Term_CM']
#         currency_2 = row['Currency_2']
#         period = row['PERIOD']
#         # indicator = row['INDICATORS'].map(mapping_indicator)
#         indicator = mapping_indicator.get(row['INDICATORS'], None)


#         value = df_movement_term.loc[
#             (df_movement_term['Term_CM'] == term_cm) 
#             & (df_movement_term['Currency_2'] == currency_2)
#             & (df_movement_term['PERIOD'] == period)
#             & (df_movement_term['MOVEMENT_TYPE'] == indicator)
#             , 'NET'
#         ].values

#         # Trả về giá trị hoặc 0 nếu không tìm thấy
#         if len(value) > 0:
#             return value.sum()
#         else:
#             return 0
# def Value_Closing_Balance(row): 
#     if row['INDICATORS'] == '1. Closing Balance':
#         term_cm = row['Term_CM']
#         currency_2 = row['Currency_2']
#         period = row['PERIOD']   

#         value = df.loc[
#             (df['Term_CM'] == term_cm) 
#             & (df['Currency_2'] == currency_2)
#             & (df['PERIOD'] == period)
#             , 'VALUE'
#         ].values

#         # Trả về giá trị hoặc 0 nếu không tìm thấy
#         if len(value) > 0:
#             return value.sum()
#         else:
#             return 0


# # Định nghĩa mapping_indicator
# mapping_indicator = {'2.1 Not-roll: New sales': "1NEW_NOTROLL",
#                     '2.1 Not-roll: Schedule on system': "2SCHE_NOTROLL",
#                     '2.1 Not-roll: Premature': "3PREMATURE_NOTROLL", 
#                     '2.2 Autoroll: New sales': "5NEW_AUTOROLL",
#                     '2.2 Autoroll: Roll': "6ROLL_AUTOROLL",
#                     '2.2 Autoroll: Premature': "7PREMATURE_AUTOROLL", 
#                     '2.3 Other': "9OTHERS"
# }

# # Áp dụng hàm cho DataFrame
# # df['VALUE'] = df.apply(Value_Closing_Balance if row['INDICATORS'] == '1. Closing Balance'else Value_Opening_Balance, axis=1)
# df['VALUE'] = df.apply(lambda row: Value_Opening_Balance(row) if row['INDICATORS'] != '3. Closing Balance' else Value_Closing_Balance(row), axis=1)


# # In ra DataFrame
# df

,Vintages,Financial_items,Type,Term_CM,Currency_2,PERIOD,INDICATORS,VALUE
0,ALL,EOP,ALL,less than 1M,VND,2023-01,1. Opening Balance,238.541364
1,ALL,EOP,ALL,less than 1M,VND,2023-01,3. Closing Balance,NaN
2,ALL,EOP,ALL,less than 1M,VND,2023-01,2.1 Not-roll: New sales,45.633947
3,ALL,EOP,ALL,less than 1M,VND,2023-01,2.1 Not-roll: Schedule on system,0.000000
4,ALL,EOP,ALL,less than 1M,VND,2023-01,2.1 Not-roll: Premature,0.000000
...,...,...,...,...,...,...,...,...
5755,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%Premature Autoroll/EOP Autoroll,0.000000
5756,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%Roll_Autoroll,0.000000
5757,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%NewNot-roll,0.000000
5758,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%New Autoroll,0.000000
5759,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%Schedule/Not-roll,0.000000

In [29]:
# Tạo hàm tùy chỉnh để lấy giá trị từ df_movement_term
def Value_Opening_Balance(row):
    if row['INDICATORS'] == '1. Opening Balance':
        term_cm = row['Term_CM']
        currency_2 = row['Currency_2']
        period = row['PERIOD']

        value = df_movement_term.loc[
            (df_movement_term['Term_CM'] == term_cm) 
            & (df_movement_term['Currency_2'] == currency_2)
            & (df_movement_term['PERIOD'] == period)
            , 'EOP_LM'
        ].values

        # Trả về giá trị hoặc 0 nếu không tìm thấy
        if len(value) > 0:
            return value.sum()
        else:
            return 0
    else:  # Added 'else' to fix indentation
        term_cm = row['Term_CM']
        currency_2 = row['Currency_2']
        period = row['PERIOD']
        indicator = mapping_indicator.get(row['INDICATORS'], None)

        value = df_movement_term.loc[
            (df_movement_term['Term_CM'] == term_cm) 
            & (df_movement_term['Currency_2'] == currency_2)
            & (df_movement_term['PERIOD'] == period)
            & (df_movement_term['MOVEMENT_TYPE'] == indicator)
            , 'NET'
        ].values

        # Trả về giá trị hoặc 0 nếu không tìm thấy
        if len(value) > 0:
            return value.sum()
        else:
            return 0

def Value_Closing_Balance(row):
    term_cm = row['Term_CM']
    currency_2 = row['Currency_2']
    period = row['PERIOD']

    # Locate rows in df_movement_term for the current 'Term_CM', 'Currency_2', and 'PERIOD'
    matching_rows = df_movement_term.loc[
        (df_movement_term['Term_CM'] == term_cm) 
        & (df_movement_term['Currency_2'] == currency_2)
        & (df_movement_term['PERIOD'] == period)
    ]

    # Sum the 'EOP_LM' values for the matching rows (Opening Balance)
    opening_balance = matching_rows['EOP_LM'].sum()

    # Sum the 'NET' values for other indicators in df_movement_term
    other_indicators_sum = matching_rows['NET'].sum()

    # Calculate the closing balance as the sum of opening balance and other indicators
    closing_balance = opening_balance + other_indicators_sum

    return closing_balance

# Định nghĩa mapping_indicator
mapping_indicator = {'2.1 Not-roll: New sales': "1NEW_NOTROLL",
                    '2.1 Not-roll: Schedule on system': "2SCHE_NOTROLL",
                    '2.1 Not-roll: Premature': "3PREMATURE_NOTROLL", 
                    '2.2 Autoroll: New sales': "5NEW_AUTOROLL",
                    '2.2 Autoroll: Roll': "6ROLL_AUTOROLL",
                    '2.2 Autoroll: Premature': "7PREMATURE_AUTOROLL", 
                    '2.3 Other': "9OTHERS"
}

# Apply the opening balance function to rows where INDICATORS is not '1. Closing Balance'
df['VALUE'] = df.apply(lambda row: Value_Opening_Balance(row) if row['INDICATORS'] != '3. Closing Balance' else 0, axis=1)

# Apply the closing balance function to rows where INDICATORS is '1. Closing Balance'
df['VALUE'] += df.apply(lambda row: Value_Closing_Balance(row) if row['INDICATORS'] == '3. Closing Balance' else 0, axis=1)

# In ra DataFrame
df

,Vintages,Financial_items,Type,Term_CM,Currency_2,PERIOD,INDICATORS,VALUE,VALUE_2
0,ALL,EOP,ALL,less than 1M,VND,2023-01,1. Opening Balance,238.541364,164.626443
1,ALL,EOP,ALL,less than 1M,VND,2023-01,3. Closing Balance,164.626443,164.626443
2,ALL,EOP,ALL,less than 1M,VND,2023-01,2.1 Not-roll: New sales,45.633947,164.626443
3,ALL,EOP,ALL,less than 1M,VND,2023-01,2.1 Not-roll: Schedule on system,0.000000,164.626443
4,ALL,EOP,ALL,less than 1M,VND,2023-01,2.1 Not-roll: Premature,0.000000,164.626443
...,...,...,...,...,...,...,...,...,...
5755,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%Premature Autoroll/EOP Autoroll,0.000000,0.000000
5756,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%Roll_Autoroll,0.000000,0.000000
5757,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%NewNot-roll,0.000000,0.000000
5758,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%New Autoroll,0.000000,0.000000
5759,ALL,EOP,ALL,4-5M,Non-VND,2024-12,%Schedule/Not-roll,0.000000,0.000000

In [ ]:
'%Premature Not-roll/EOP Not-roll'
def Value_NotRollPremature_NotRollEOP(row):
    term_cm = row['Term_CM']
    currency_2 = row['Currency_2']
    period = row['PERIOD']
    indicator = mapping_indicator.get(row['INDICATORS'], None)

    # Locate rows in df_movement_term for the current 'Term_CM', 'Currency_2', and 'PERIOD'
    matching_rows = df_movement_term.loc[
        (df_movement_term['Term_CM'] == term_cm) 
        & (df_movement_term['Currency_2'] == currency_2)
        & (df_movement_term['PERIOD'] == period)
        & (df_movement_term['MOVEMENT_TYPE'] == indicator)
        , 'NET'
    ]

    # Sum the 'EOP_LM' values for the matching rows (Opening Balance)
    opening_balance = matching_rows['EOP_LM'].sum()

    # Sum the 'NET' values for other indicators in df_movement_term
    other_indicators_sum = matching_rows['NET'].sum()

    # Calculate the closing balance as the sum of opening balance and other indicators
    closing_balance = opening_balance + other_indicators_sum

    return closing_balance

In [69]:
##Checking box
# Lọc và in ra những dòng có giá trị "VALUE" lớn hơn 0 và trường "PERIOD" là '2023-01'
filtered_df = df.loc[(df['VALUE'] > 0) & (df['PERIOD'] == '2023-01')]

filtered_df

,Vintages,Financial_items,Type,Term_CM,Currency_2,PERIOD,INDICATORS,VALUE
0,ALL,EOP,ALL,less than 1M,VND,2023-01,1. Opening Balance,238.541364
24,ALL,EOP,ALL,1-3M,VND,2023-01,1. Opening Balance,16828.648054
48,ALL,EOP,ALL,6-9M,VND,2023-01,1. Opening Balance,78275.258947
72,ALL,EOP,ALL,From 18M,VND,2023-01,1. Opening Balance,1267.824141
96,ALL,EOP,ALL,10-11M,VND,2023-01,1. Opening Balance,157.605045
120,ALL,EOP,ALL,12-18M,VND,2023-01,1. Opening Balance,41007.363552
168,ALL,EOP,ALL,4-5M,VND,2023-01,1. Opening Balance,201.841634
192,ALL,EOP,ALL,less than 1M,Non-VND,2023-01,1. Opening Balance,7.964695
216,ALL,EOP,ALL,1-3M,Non-VND,2023-01,1. Opening Balance,331.569383
240,ALL,EOP,ALL,6-9M,Non-VND,2023-01,1. Opening Balance,493.668579
264,ALL,EOP,ALL,From 18M,Non-VND,2023-01,1. Opening Balance,85.490172
312,ALL,EOP,ALL,12-18M,Non-VND,2023-01,1. Opening Balance,352.953252
360,ALL,EOP,ALL,4-5M,Non-VND,2023-01,1. Opening Balance,1.078939